# Generated by Django 3.2.5 on 2022-03-23 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('about', models.CharField(default='title', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('picture', models.FileField(upload_to='uploads/')),
                ('title', models.CharField(default='title', max_length=9999999999999999)),
                ('dateadded', models.DateField(default=datetime.datetime.now)),
                ('introduction', models.CharField(default='introduction', max_length=2000)),
                ('content', models.TextField(default='https://medium.com/@ianmuthuri254/', max_length=9999999999999999)),
                ('url', models.TextField(default='https://medium.com/@ianmuthuri254/', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=200)),
                ('issuer', models.CharField(default='issuer', max_length=300)),
                ('dateissued', models.DateField(default=datetime.datetime.now)),
                ('url', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=200)),
                ('description', models.CharField(default='description', max_length=300)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('url', models.CharField(max_length=200)),
                ('picture', models.FileField(upload_to='uploads/')),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=200)),
                ('portorolioPicture', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('strength', models.IntegerField()),
                ('picture', models.CharField(max_length=200)),
            ],
        ),
    ]
