# Generated by Django 4.0.3 on 2022-06-14 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ianmuthuri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.datetime.now)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('region_code', models.CharField(max_length=20)),
                ('region_name', models.CharField(max_length=20)),
                ('area_code', models.CharField(max_length=20)),
                ('dma_code', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=20)),
                ('country_name', models.CharField(max_length=20)),
                ('in_eu', models.CharField(max_length=20)),
                ('eu_vat_rate', models.CharField(max_length=20)),
                ('continent_code', models.CharField(max_length=20)),
                ('continent_name', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('location_accuracy_radius', models.CharField(max_length=20)),
                ('timezone', models.CharField(max_length=20)),
                ('currency_code', models.CharField(max_length=20)),
                ('currency_symbol', models.CharField(max_length=20)),
                ('currency_symbol_utf8', models.CharField(max_length=20)),
                ('currency_converter', models.CharField(max_length=20)),
            ],
        ),
    ]
