# Generated by Django 4.0.3 on 2022-06-14 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ianmuthuri', '0002_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='area_code',
            field=models.CharField(default='True', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='city',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='continent_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='continent_name',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='country_code',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='country_name',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='currency_code',
            field=models.CharField(default='USD', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='currency_converter',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='currency_symbol_utf8',
            field=models.CharField(default='$', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='dma_code',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='eu_vat_rate',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='in_eu',
            field=models.CharField(default='False', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='ip_address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='latitude',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='location_accuracy_radius',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='longitude',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='region',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='region_code',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='region_name',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='timezone',
            field=models.CharField(default=datetime.datetime.now, max_length=20),
        ),
    ]
