# Generated by Django 4.0.3 on 2022-06-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ianmuthuri', '0003_alter_visitors_area_code_alter_visitors_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='country',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
