# Generated by Django 4.0.3 on 2022-06-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ianmuthuri', '0004_alter_visitors_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='continent_code',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='currency_converter',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='currency_symbol',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='currency_symbol_utf8',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='dma_code',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='eu_vat_rate',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='in_eu',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='location_accuracy_radius',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='timezone',
        ),
    ]
