# Generated by Django 4.0.3 on 2022-06-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ianmuthuri', '0005_remove_visitors_area_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='country',
            field=models.CharField(default='Not Defined', max_length=20),
        ),
    ]
